id: A1CF01558
title: A Means to Pacify the Fear of Natural Disasters
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.390390
  last_modified_at: 2022-03-01 06:05:36.390394
