id: A1CF01558
title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.448432
  last_modified_at: 2022-03-01 06:05:36.448435
