id: A1CF01558
title: A Supplication to Noble Tārā, The Wish-Fulfilling Cornucopia
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.397106
  last_modified_at: 2022-03-01 06:05:36.397110
