id: A1CF01558
title: 'Burgeoning Benefit and Happiness: An Aspiration to be Reborn in the Land of
  Turquoise Leaves'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.422588
  last_modified_at: 2022-03-01 06:05:36.422591
