id: A1CF01558
title: Prayer to Tārā, Combined with Her Mantra
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.435373
  last_modified_at: 2022-03-01 06:05:36.435375
