id: A1CF01558
title: 'The Concentration of Blessings: Red Tārā Lineage Prayer'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.443407
  last_modified_at: 2022-03-01 06:05:36.443412
