id: A1CF01558
title: Aspiration Prayer from Tārā Sādhana
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.414407
  last_modified_at: 2022-03-01 06:05:36.414412
