id: A1CF01558
title: Concise White Tārā Sādhana
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.423889
  last_modified_at: 2022-03-01 06:05:36.423892
