id: A1CF01558
title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.427349
  last_modified_at: 2022-03-01 06:05:36.427352
