id: A1CF01558
title: 'Prayer to Tārā: A Sevenfold Supplication for Protection'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.436956
  last_modified_at: 2022-03-01 06:05:36.436958
