id: A1CF01558
title: A Concise Sang Offering to Tārā
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.386401
  last_modified_at: 2022-03-01 06:05:36.386408
