id: A1CF01558
title: 'The Sweet-Sounding Song that Fulfils All Aims: A Prayer to Noble Tārā Combined
  with Her Root Mantra'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.457933
  last_modified_at: 2022-03-01 06:05:36.457937
