id: A1CF01558
title: 'Averting Obstructive Circumstances: A Prayer to Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.416969
  last_modified_at: 2022-03-01 06:05:36.416972
