id: A1CF01558
title: Brief Windhorse Practice of Tārā
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.420623
  last_modified_at: 2022-03-01 06:05:36.420625
