id: A1CF01558
title: An Extremely Concise Praise of the Twenty-One Tārās
type: translation
source_metadata:
  languages:
  - en
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.411988
  last_modified_at: 2022-03-01 06:05:36.412035
