id: A1CF01558
title: Brief Homage to the Twenty-One Tārās
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.418767
  last_modified_at: 2022-03-01 06:05:36.418770
