id: A1CF01558
title: 'Eliminator of Suffering: A Prayer to the Venerable and Exalted Tārā'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 06:05:36.425675
  last_modified_at: 2022-03-01 06:05:36.425678
